version: "3.7"

services:
  canyon:
    container_name: canyon
    image: zhangtao25/canyon:main
    restart: always
    volumes:
      - ./envs/canyon/.env:/app/.env
    ports:
      - "8080:8080"
  canyon-s3:
    container_name: canyon-s3
    image: zhangtao25/canyon-s3:main
    restart: always
    volumes:
      - ./envs/canyon-s3/.env:/app/.env
    ports:
      - "28000:8080"
  canyon-homepage:
    container_name: canyon-homepage
    image: zhangtao25/canyon-homepage:main
    restart: always
    ports:
      - "28001:3000"